"""
Machine-generated file used to validate that all scripts run without crashing.
Generated by build_run_all_scripts.py
Have a nice day!
"""


from __future__ import print_function
import sfc_models.examples.Quick2DPlot as extras
extras.plt = None # Prang the plots


import build_SIM_model
if "main" in dir(build_SIM_model):
    build_SIM_model.main()


import ex20161103_SIM_2_country
if "main" in dir(ex20161103_SIM_2_country):
    ex20161103_SIM_2_country.main()


import ex20161128_tax_cut_comparison
if "main" in dir(ex20161128_tax_cut_comparison):
    ex20161128_tax_cut_comparison.main()


import ex20161206_SIM_with_deposits
if "main" in dir(ex20161206_SIM_with_deposits):
    ex20161206_SIM_with_deposits.main()


import ex20170209_SIMEX1
if "main" in dir(ex20170209_SIMEX1):
    ex20170209_SIMEX1.main()


import ex20170221_Model_PC
if "main" in dir(ex20170221_Model_PC):
    ex20170221_Model_PC.main()


import ex20170225_Model_REG
if "main" in dir(ex20170225_Model_REG):
    ex20170225_Model_REG.main()


import ex20170307_Model_REG2
if "main" in dir(ex20170307_Model_REG2):
    ex20170307_Model_REG2.main()


import intro_3_02_example
if "main" in dir(intro_3_02_example):
    intro_3_02_example.main()


import intro_3_03_hello_world_1
if "main" in dir(intro_3_03_hello_world_1):
    intro_3_03_hello_world_1.main()


import intro_3_03_hello_world_2
if "main" in dir(intro_3_03_hello_world_2):
    intro_3_03_hello_world_2.main()


import intro_3_03_hello_world_3
if "main" in dir(intro_3_03_hello_world_3):
    intro_3_03_hello_world_3.main()


import intro_3_03_hello_world_4
if "main" in dir(intro_3_03_hello_world_4):
    intro_3_03_hello_world_4.main()


import sfcmod_FX
if "main" in dir(sfcmod_FX):
    sfcmod_FX.main()


import sfcmod_OPENG
if "main" in dir(sfcmod_OPENG):
    sfcmod_OPENG.main()


import sfcmod_REG2
if "main" in dir(sfcmod_REG2):
    sfcmod_REG2.main()


import SIM_Model_With_Capitalists
if "main" in dir(SIM_Model_With_Capitalists):
    SIM_Model_With_Capitalists.main()


