"""
Machine-generated file used to validate that all scripts run without crashing.
Generated by build_run_all_scripts.py
Have a nice day!
"""


from __future__ import print_function
import sfc_models.examples.Quick2DPlot as extras
extras.plt = None # Prang the plots


import build_SIM_model
if "main" in dir(build_SIM_model):
    build_SIM_model.main()


import ex20161103_SIM_2_country
if "main" in dir(ex20161103_SIM_2_country):
    ex20161103_SIM_2_country.main()


import ex20161128_tax_cut_comparison
if "main" in dir(ex20161128_tax_cut_comparison):
    ex20161128_tax_cut_comparison.main()


import ex20161206_SIM_with_deposits
if "main" in dir(ex20161206_SIM_with_deposits):
    ex20161206_SIM_with_deposits.main()


import ex20170221_Model_PC
if "main" in dir(ex20170221_Model_PC):
    ex20170221_Model_PC.main()


import ex20170225_Model_REG
if "main" in dir(ex20170225_Model_REG):
    ex20170225_Model_REG.main()


import ex20170307_Model_REG2
if "main" in dir(ex20170307_Model_REG2):
    ex20170307_Model_REG2.main()


import intro_3_02_example
if "main" in dir(intro_3_02_example):
    intro_3_02_example.main()


import intro_3_03_hello_world_1
if "main" in dir(intro_3_03_hello_world_1):
    intro_3_03_hello_world_1.main()


import intro_3_03_hello_world_2
if "main" in dir(intro_3_03_hello_world_2):
    intro_3_03_hello_world_2.main()


import intro_3_03_hello_world_3
if "main" in dir(intro_3_03_hello_world_3):
    intro_3_03_hello_world_3.main()


import intro_3_03_hello_world_4
if "main" in dir(intro_3_03_hello_world_4):
    intro_3_03_hello_world_4.main()


import intro_3_05_variable_names_1
if "main" in dir(intro_3_05_variable_names_1):
    intro_3_05_variable_names_1.main()


import intro_3_05_variable_names_2
if "main" in dir(intro_3_05_variable_names_2):
    intro_3_05_variable_names_2.main()


import intro_5_03_no_tax_SIM
if "main" in dir(intro_5_03_no_tax_SIM):
    intro_5_03_no_tax_SIM.main()


import intro_5_04_SIMEX1
if "main" in dir(intro_5_04_SIMEX1):
    intro_5_04_SIMEX1.main()


import intro_6_04_externalsector
if "main" in dir(intro_6_04_externalsector):
    intro_6_04_externalsector.main()


import intro_6_06_gold_standard_G
if "main" in dir(intro_6_06_gold_standard_G):
    intro_6_06_gold_standard_G.main()


import intro_X_XX_sim_fiscal
if "main" in dir(intro_X_XX_sim_fiscal):
    intro_X_XX_sim_fiscal.main()


import intro_X_XX_sim_growing_fiscal
if "main" in dir(intro_X_XX_sim_growing_fiscal):
    intro_X_XX_sim_growing_fiscal.main()


import intro_X_XX_sim_multiplier
if "main" in dir(intro_X_XX_sim_multiplier):
    intro_X_XX_sim_multiplier.main()


import sfcmod_external_sector
if "main" in dir(sfcmod_external_sector):
    sfcmod_external_sector.main()


import sfcmod_FX
if "main" in dir(sfcmod_FX):
    sfcmod_FX.main()


import sfcmod_OPENG
if "main" in dir(sfcmod_OPENG):
    sfcmod_OPENG.main()


import sfcmod_REG2
if "main" in dir(sfcmod_REG2):
    sfcmod_REG2.main()


import SIM_Model_With_Capitalists
if "main" in dir(SIM_Model_With_Capitalists):
    SIM_Model_With_Capitalists.main()


